Detect ign instead of using cmake module to check for ignition-tools
gazebosim/gz-transport pull request #249
Opened 2021-06-28 15:25 UTC by j-rivero

Part of ignition-tooling/release-tools#472

I don't detect the conditional installation of the ign submodule, the PR just
changed the way of detecting ign for testing.

2021-06-28 16:21 UTC, mjcarroll commented on test/test_config.h.in
> -#define IGN_PATH "@IGNITION-TOOLS_BINARY_DIRS@"
I don't know if you removed this intentionally, but `src/ign_TEST.cc` depends on this variable being set.

2021-07-05 19:36 UTC, caguero commented on test/test_config.h.in
> -#define IGN_PATH "@IGNITION-TOOLS_BINARY_DIRS@"
I think `find_program` returns the path in the variable, so I think we could use `HAVE_IGN_TOOLS` to get the path. Then, either we keep this variable using `HAVE_IGN_TOOLS`, or we remove it and use `HAVE_IGN_TOOLS` instead.

2021-08-23 16:13 UTC, caguero commented on test/test_config.h.in
> -#define IGN_PATH "@IGNITION-TOOLS_BINARY_DIRS@"
Friendly ping @j-rivero

2021-08-23 18:42 UTC, j-rivero commented on test/test_config.h.in
> -#define IGN_PATH "@IGNITION-TOOLS_BINARY_DIRS@"
> I think `find_program` returns the path in the variable, so I think we could use `HAVE_IGN_TOOLS` to get the path. Then, either we keep this variable using `HAVE_IGN_TOOLS`, or we remove it and use `HAVE_IGN_TOOLS` instead.

You are right, at least my test on Linux is working just fine. 69bdd88

2021-11-09 14:05 UTC, mjcarroll commented
@osrf-jenkins retest this please

2021-11-15 16:17 UTC, caguero approved these changes

2021-11-15 16:18 UTC, mjcarroll approved these changes

2021-11-15 17:05 UTC, chapulina requested changes
CI is still unhappy

```
   [ RUN      ] ignTest.ServiceRequest
  /github/workspace/tools/ign_TEST.cc:367: Failure
  Value of: "data: " + value + "\n\n"
    Actual: "data: 10\n\n"
  Expected: output
  Which is: "sh: 1: /usr/bin/ign/ign: not found\n"
```

2022-06-14 23:00 UTC, chapulina commented
Closing and opening to retrigger CI

2022-06-15 00:01 UTC, chapulina approved these changes
Fixed tests in [382e023](https://github.com/gazebosim/gz-transport/pull/249/commits/382e023b927c2fcc3cbb06182fa2b1b98c346eb5)

2022-06-15 00:02 UTC, merged