Ivanpauno/parameters component11
gazebosim/gz-transport pull request #305
Opened 2022-04-08 18:01 UTC by ivanpauno

# 🎉 New feature

Replaces https://github.com/ignitionrobotics/ign-gazebo/pull/1280.
Same as https://github.com/ignitionrobotics/ign-transport/pull/304 but rebased to target `ignition-transport11`.

## Summary

Adds an implementation of a parameter registry, which allows through services to:

- Declare a parameter.
- Get the value of a parameter.
- Set the value of a parameter.
- List all parameters.

The same operations can be done directly locally, using the parameters registry API.
There's also a parameters client implementation, which is just a wrapper on top of sending requests to the services.

TODO:

- [ ] Add tests!!!
- [ ] Open PR in ignition gazebo using this!!!

## Test it

TODO

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

2022-04-18 16:06 UTC, caguero requested changes

2022-04-18 16:07 UTC, caguero requested changes
See also the style errors reported by CI.

2022-04-25 14:47 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Registry.hh
> +        public: ParameterValue GetParameter(
Just to clarify, this is not a "getter", it's allowing to get any parameter from the registry.
e.g.: `registry.GetParameter("my_parameter_name");`

Though `registry.Parameter("my_parameter_name");` would also be clear.

2022-04-25 18:16 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Client.hh
> +        ListParameters();
That's possible, but I have to make the `ignition::transport::Node node` member `mutable` for that to work.
Is that fine?

2022-04-25 18:19 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Registry.hh
> +      class ParametersRegistry
Done in https://github.com/ignitionrobotics/ign-transport/pull/305/commits/452ee75d703a816b26dbd20e258429113862cc33.

2022-04-25 18:19 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Registry.hh
> +#include "ignition/msgs/parameter_declarations.pb.h"
Done in https://github.com/ignitionrobotics/ign-transport/pull/305/commits/452ee75d703a816b26dbd20e258429113862cc33.

2022-04-25 18:20 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Registry.hh
> +        public: ParametersRegistry(std::string _parametersServicesNamespace);
Done in https://github.com/ignitionrobotics/ign-transport/pull/305/commits/76bd87ec9546f66029282956f345e4342b486d31.

2022-04-25 18:24 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Registry.hh
> +          google::protobuf::Message & _value);
Done in https://github.com/ignitionrobotics/ign-transport/pull/305/commits/0510e18cc9e7562e975de8a25956a9702b114307

2022-04-25 18:24 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Registry.hh
> +          const std::string & _parameterName);
Fixed in https://github.com/ignitionrobotics/ign-transport/pull/305/commits/0510e18cc9e7562e975de8a25956a9702b114307

2022-04-25 18:24 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Registry.hh
> +        ProtoMsgT GetParameter(const std::string & _parameterName)
Done, see https://github.com/ignitionrobotics/ign-transport/pull/305/commits/0510e18cc9e7562e975de8a25956a9702b114307

2022-04-25 18:25 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Client.hh
> +        ListParameters();
See https://github.com/ignitionrobotics/ign-transport/pull/305/commits/1ab769c4a37f97f602975bb9b6134942edddb0fb

2022-04-25 18:25 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Client.hh
> +        GetParameter(const std::string & _parameterName);
See discussion [here](https://github.com/ignitionrobotics/ign-transport/pull/305#discussion_r857902800)

2022-04-25 18:26 UTC, ivanpauno commented on parameters/src/Client.cc
> +#include <sstream>
Done https://github.com/ignitionrobotics/ign-transport/pull/305/commits/1ab769c4a37f97f602975bb9b6134942edddb0fb

2022-04-25 18:27 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Client.hh
> +        GetParameter(const std::string & _parameterName);
See comment [here](https://github.com/ignitionrobotics/ign-transport/pull/305#discussion_r857714161), I will update both places with the resolution of that discussion.

2022-04-26 15:19 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Client.hh
> +        std::string serverNamespace;
Done, see https://github.com/ignitionrobotics/ign-transport/pull/305/commits/6489c73d578896ff3853b9f084bd439a7ef0c83b

2022-04-26 17:56 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Registry.hh
> +        public: ParameterValue GetParameter(
Done in https://github.com/ignitionrobotics/ign-transport/pull/305/commits/3f9f57c5bc7e71945c1fc15e81ee5cca2595076d

2022-05-24 20:42 UTC, ivanpauno commented
@caguero could you take another look to this?
I think I've addressed all the previous comments.
I've also rebased the PR.

CI seems to be failing because https://github.com/gazebosim/gz-msgs/pull/241 is required first.

2022-05-27 17:10 UTC, caguero requested changes
This is looking good to me. Are you planning to add any tests to cover the new functionality?

2022-06-22 18:16 UTC, ivanpauno commented
@caguero I've added unit tests to cover both `ParametersRegistry` and `ParametersClient`, and fixed some bugs.

I think I will take another look to both classes API and uniformize them (and maybe add a common base class to both), but those changes should be minor. If you have any input about that let me know.

2022-06-28 23:04 UTC, caguero commented
> @caguero I've added unit tests to cover both `ParametersRegistry` and `ParametersClient`, and fixed some bugs.
> 
> I think I will take another look to both classes API and uniformize them (and maybe add a common base class to both), but those changes should be minor. If you have any input about that let me know.

Thanks! Do you mind to update https://github.com/gazebosim/gz-msgs/pull/241 with the changes that @mjcarroll requested? We can merge that one first, and then, merge this PR.

2022-07-04 19:22 UTC, ivanpauno commented
> Thanks! Do you mind to update https://github.com/gazebosim/gz-msgs/pull/241 with the changes that @mjcarroll requested? We can merge that one first, and then, merge this PR.

Done

> I think I will take another look to both classes API and uniformize them (and maybe add a common base class to both), but those changes should be minor. If you have any input about that let me know.

Done as well

2022-07-15 15:37 UTC, ivanpauno commented
@caguero friendly ping

2022-08-18 16:06 UTC, scpeters commented
I've merged https://github.com/gazebosim/gz-msgs/pull/241 and made a prerelease and opened a draft PR #349 that is level with this branch but using a special branch name that allows it to use matching branches in gzdev and homebrew-simulation to use the gz-msgs prerelease. I think the CI should now be working for this PR.

We should still make a stable release of gz-msgs before merging this, but I wanted to get working CI to support this PR review.

2022-08-18 16:21 UTC, scpeters commented
the windows build (which doesn't need the `ci_matching_branch/*` trick) is not happy:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_transport-pr-win&build=333)](https://build.osrfoundation.org/job/ign_transport-pr-win/333/) https://build.osrfoundation.org/job/ign_transport-pr-win/333/

~~~
parameters\src\Client.cc(159,43): error C2589: 'constant': illegal token on right side of '::' [C:\Jenkins\workspace\ign_transport-pr-win\ws\build\ignition-transport11\parameters\src\ignition-transport11-parameters.vcxproj]

parameters\src\Client.cc(159): error C2062: type 'unknown-type' unexpected [C:\Jenkins\workspace\ign_transport-pr-win\ws\build\ignition-transport11\parameters\src\ignition-transport11-parameters.vcxproj]

parameters\src\Client.cc(159,53): error C2143: syntax error: missing ';' before '{' [C:\Jenkins\workspace\ign_transport-pr-win\ws\build\ignition-transport11\parameters\src\ignition-transport11-parameters.vcxproj]

parameters\src\Client.cc(199,43): error C2589: 'constant': illegal token on right side of '::' [C:\Jenkins\workspace\ign_transport-pr-win\ws\build\ignition-transport11\parameters\src\ignition-transport11-parameters.vcxproj]

parameters\src\Client.cc(199): error C2062: type 'unknown-type' unexpected [C:\Jenkins\workspace\ign_transport-pr-win\ws\build\ignition-transport11\parameters\src\ignition-transport11-parameters.vcxproj]

parameters\src\Client.cc(199,53): error C2143: syntax error: missing ';' before '{' [C:\Jenkins\workspace\ign_transport-pr-win\ws\build\ignition-transport11\parameters\src\ignition-transport11-parameters.vcxproj]

~~~

2022-08-18 16:23 UTC, scpeters commented
homebrew build just has one test failure that looks unrelated:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_transport-ci-pr_any-homebrew-amd64&build=1363)](https://build.osrfoundation.org/job/ignition_transport-ci-pr_any-homebrew-amd64/1363/) https://build.osrfoundation.org/job/ignition_transport-ci-pr_any-homebrew-amd64/1363/

2022-08-18 16:30 UTC, scpeters commented
I think the ABI checker complaint is a false positive

* https://build.osrfoundation.org/job/ignition_transport-abichecker-any_to_any-ubuntu_auto-amd64/465/API_5fABI_20report/

2022-08-19 19:54 UTC, ivanpauno commented
> the windows build (which doesn't need the ci_matching_branch/* trick) is not happy:

That's happening because `winerror.h` has a macro named NO_ERROR, see [here](https://stackoverflow.com/questions/49237883/macro-no-error-conflict).
The same name is being used in the enum I created [here](https://github.com/gazebosim/gz-msgs/blob/61607f967e1aabe2e238e1f590dddc2ca7e59ad0/proto/ignition/msgs/parameter_error.proto#L30).
Should I rename that to SUCCESS?

I can also try to fix that by adding an `undef` in the correct place and reordering the includes, but I would prefer not doing that.

2022-08-23 07:40 UTC, scpeters commented
> > the windows build (which doesn't need the ci_matching_branch/* trick) is not happy:
> 
> That's happening because `winerror.h` has a macro named NO_ERROR, see [here](https://stackoverflow.com/questions/49237883/macro-no-error-conflict). The same name is being used in the enum I created [here](https://github.com/gazebosim/gz-msgs/blob/61607f967e1aabe2e238e1f590dddc2ca7e59ad0/proto/ignition/msgs/parameter_error.proto#L30). Should I rename that to SUCCESS?

`SUCCESS` sounds good to me. I can make another prerelease after that `gz-msgs` change is merged

2022-08-23 16:38 UTC, ivanpauno commented
Done, see https://github.com/gazebosim/gz-msgs/pull/298.

2022-08-24 20:48 UTC, scpeters commented on parameters/include/ignition/transport/parameters/Client.hh
> +      class ParametersClient : public ParametersInterface
each of these classes defined in header files that is intended to be public and a visible symbol should use the `IGNITION_TRANSPORT_PARAMETERS_VISIBLE` macro from `ignition/transport/parameters/Export.hh`

similar to `log/*.hh` header files:

* https://github.com/gazebosim/gz-transport/blob/8083eae49d87a029f3031a9857c9a0310551cf31/log/include/ignition/transport/log/Batch.hh#L24-L41

2022-08-25 17:33 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Client.hh
> +      class ParametersClient : public ParametersInterface
Thanks for the help!
CI should pass now

2022-08-25 18:48 UTC, ivanpauno commented
Ah sorry, it seems there're still some compile errors on Windows, but now it's different.
I will check what's going on

2022-08-25 19:59 UTC, ivanpauno commented
Ok, now the windows build passed.
There're a bunch of build warnings though, but the only one that seems related to the PR should've been fixed by https://github.com/gazebosim/gz-transport/pull/305/commits/4089abfeaaba996fb65f9e392ffd2d4a4d2011b2.
cc @scpeters

2022-08-25 22:29 UTC, scpeters commented
> Ok, now the windows build passed.
> There're a bunch of build warnings though, but the only one that seems related to the PR should've been fixed by [4089abf](https://github.com/gazebosim/gz-transport/commit/4089abfeaaba996fb65f9e392ffd2d4a4d2011b2).
> cc @scpeters

nice work! I just pushed one small fix to some comments in https://github.com/gazebosim/gz-transport/pull/305/commits/1688b6303e16b09aa53ecd04335a8d9c7087e92d where a different file was referring to `NO_ERROR` instead of `SUCCESS`

I'll sync #349 with this branch to hopefully get more of the CI passing

2022-08-26 13:03 UTC, ivanpauno commented
> nice work! I just pushed one small fix to some comments in https://github.com/gazebosim/gz-transport/commit/1688b6303e16b09aa53ecd04335a8d9c7087e92d where a different file was referring to NO_ERROR instead of SUCCESS

I think those two are unrelated to the PR, as that's part of `transport/log`, maybe there's another symbol called `NO_ERROR` in ignition.

2022-08-26 21:12 UTC, scpeters commented on parameters/src/CMakeLists.txt
> +message(WARNING "param_lib_target ${param_lib_target}")
let's remove this line or convert to a `STATUS` message

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ignition_transport-ci-pr_any-ubuntu_auto-amd64&build=947)](https://build.osrfoundation.org/job/ignition_transport-ci-pr_any-ubuntu_auto-amd64/947/) https://build.osrfoundation.org/job/ignition_transport-ci-pr_any-ubuntu_auto-amd64/947/

2022-08-26 21:14 UTC, scpeters commented
CI is working with the help of https://github.com/gazebosim/gz-transport/pull/349 (except for the ABI checker, which is complaining about untouched functions)

@caguero I think this is ready for further review

2022-08-29 16:23 UTC, caguero commented on parameters/include/ignition/transport/parameters/Interface.hh
> +        public: virtual void DeclareParameter(
Usually the convention that we have is to avoid throwing exceptions if it's possible to continue. Can we potentially return a boolean to report that the parameter declaration didn't succeed and avoid the exception?

2022-08-29 16:23 UTC, caguero commented on parameters/src/Client.cc
> +ParametersClient::~ParametersClient() = default;
Nit: Can we add function separators?

2022-08-29 16:23 UTC, caguero commented on parameters/src/Client.cc
> +GetParameterCommon(
Nit: Normally we use lowercase for static functions.

2022-08-29 16:23 UTC, caguero commented on parameters/src/Client_TEST.cc
> +TEST_F(ParametersClientTest, Parameter)
Nit: Use function separator.

2022-08-29 16:23 UTC, caguero commented on parameters/src/Utils.hh
> +      std::string add_ign_msgs_prefix(const std::string & ignType);
Nit: Convert to camelCase and document with doxygen.

2022-08-29 16:23 UTC, caguero commented on parameters/src/Utils.hh
> +/*
I suggest to also create a unit test for this class.

2022-08-31 13:54 UTC, ivanpauno commented on parameters/src/CMakeLists.txt
> +message(WARNING "param_lib_target ${param_lib_target}")
Fixed in https://github.com/gazebosim/gz-transport/pull/305/commits/2ea957df386dbeae9fa0dbe99df0ecc4c9a4d1e5.

2022-08-31 13:58 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/Interface.hh
> +        public: virtual void DeclareParameter(
The problem with a boolean is that you lose information, you only inform that an error happened but not which.
If that's the convention, I can apply it here as well

2022-08-31 14:03 UTC, ivanpauno commented on parameters/src/Client.cc
> +ParametersClient::~ParametersClient() = default;
Added in https://github.com/gazebosim/gz-transport/pull/305/commits/ccb520f2c2c1ba0897b371625e78a5ba53d28a74

2022-08-31 14:42 UTC, ivanpauno commented on parameters/src/Client_TEST.cc
> +TEST_F(ParametersClientTest, Parameter)
Done in https://github.com/gazebosim/gz-transport/commit/ccb520f2c2c1ba0897b371625e78a5ba53d28a74.

2022-08-31 14:44 UTC, ivanpauno commented on parameters/src/Client.cc
> +GetParameterCommon(
Fixed in https://github.com/gazebosim/gz-transport/pull/305/commits/dff201bc9373b920ce1c4b1d94e9ad6a030f72bb

2022-08-31 14:45 UTC, ivanpauno commented on parameters/src/Utils.hh
> +      std::string add_ign_msgs_prefix(const std::string & ignType);
Done in https://github.com/gazebosim/gz-transport/pull/305/commits/dff201bc9373b920ce1c4b1d94e9ad6a030f72bb.

2022-08-31 16:15 UTC, ivanpauno commented on parameters/src/Utils.hh
> +/*
Done in https://github.com/gazebosim/gz-transport/pull/305/commits/8adc376da2b6150f1e7d92a45b89cfefe413a7cd

2022-08-31 17:46 UTC, scpeters commented on parameters/src/Utils.hh
> +      std::optional<std::string> getIgnTypeFromAnyProto(
these functions need `IGNITION_TRANSPORT_PARAMETERS_VISIBLE` in order to be called by the unit test on windows:

* [![Build Status](https://build.osrfoundation.org/buildStatus/icon?job=ign_transport-pr-win&build=361)](https://build.osrfoundation.org/job/ign_transport-pr-win/361/) https://build.osrfoundation.org/job/ign_transport-pr-win/361/

~~~
Utils_TEST.obj : error LNK2001: unresolved external symbol "class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > __cdecl ignition::transport::parameters::v11::addIgnMsgsPrefix(class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > const &)" (?addIgnMsgsPrefix@v11@parameters@transport@ignition@@YA?AV?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@AEBV56@@Z) [C:\Jenkins\workspace\ign_transport-pr-win\ws\build\ignition-transport11\parameters\src\UNIT_Utils_TEST.vcxproj]

Utils_TEST.obj : error LNK2001: unresolved external symbol "class std::optional<class std::basic_string<char,struct std::char_traits<char>,class std::allocator<char> > > __cdecl ignition::transport::parameters::v11::getIgnTypeFromAnyProto(class google::protobuf::Any const &)" (?getIgnTypeFromAnyProto@v11@parameters@transport@ignition@@YA?AV?$optional@V?$basic_string@DU?$char_traits@D@std@@V?$allocator@D@2@@std@@@std@@AEBVAny@protobuf@google@@@Z) [C:\Jenkins\workspace\ign_transport-pr-win\ws\build\ignition-transport11\parameters\src\UNIT_Utils_TEST.vcxproj]
~~~

2022-08-31 17:54 UTC, ivanpauno commented on parameters/src/Utils.hh
> +      std::optional<std::string> getIgnTypeFromAnyProto(
Thanks, fixed in https://github.com/gazebosim/gz-transport/pull/305/commits/b4bb900d3e686eda279d72fc4e0081b5688497cf

2022-08-31 18:49 UTC, scpeters commented
I just synced #349 with this branch, which should give a full round of CI with the prereleases

2022-08-31 20:15 UTC, scpeters commented
codecov shows 0% code coverage of ParamCommandAPI.cc 

* https://app.codecov.io/gh/gazebosim/gz-transport/pull/349

2022-09-07 19:59 UTC, ivanpauno commented
> codecov shows 0% code coverage of ParamCommandAPI.cc

Ok, I can add test cases for it.

2022-09-12 18:23 UTC, ivanpauno commented
> codecov shows 0% code coverage of ParamCommandAPI.cc

Added tests in https://github.com/gazebosim/gz-transport/pull/305/commits/d5c7c0ca833c7ef31f08cde81413c13841419592

2022-09-14 14:49 UTC, ivanpauno commented
@scpeters thanks, solved both issues in https://github.com/gazebosim/gz-transport/pull/305/commits/dc77e1d82cc67cf554ba90080e7144b82e14baa1 and https://github.com/gazebosim/gz-transport/pull/305/commits/34f61905cf190691acb18800bb413076e7b55edb

2022-09-14 18:07 UTC, scpeters commented
> @scpeters thanks, solved both issues in [dc77e1d](https://github.com/gazebosim/gz-transport/commit/dc77e1d82cc67cf554ba90080e7144b82e14baa1) and [34f6190](https://github.com/gazebosim/gz-transport/commit/34f61905cf190691acb18800bb413076e7b55edb)

hm...the macOS and Ubuntu Jammy builds are fine, but Focal and Bionic are failing to compile

~~~
parameters/src/cmd/ParamCommandAPI.hh:26:8: error: expected unqualified-id before string constant
     26 | extern "C" void cmdParametersList(const char * _ns);
        |        ^~~
~~~

2022-09-14 19:10 UTC, ivanpauno commented
> hm...the macOS and Ubuntu Jammy builds are fine, but Focal and Bionic are failing to compile

Sorry, my bad :man_facepalming:

2022-09-14 21:07 UTC, scpeters commented
CI is looking pretty good now.

* Windows has some pre-existing compiler warnings, otherwise clean
* the abi-checker is claiming an API break caused by [modified symbols](https://build.osrfoundation.org/job/ignition_transport-abichecker-any_to_any-ubuntu_auto-amd64/524/API_5fABI_20report/) in `HandlerStorage.hh`, which is not touched by this PR, so I think this is a false positive.
* the coverage checker complains that code coverage is at 83.97% for this diff instead of 88.88%

I think it's ready for another round of reviews by @caguero

2022-09-27 18:44 UTC, scpeters commented
I pushed to #349 so this CI is re-running

I'm also preparing a PR for a stable release of gz-msgs 8.7.0

2022-09-27 18:54 UTC, scpeters commented
> I'm also preparing a PR for a stable release of gz-msgs 8.7.0

I'll open the release PR after https://github.com/gazebosim/gz-msgs/pull/307

2022-09-29 04:23 UTC, scpeters commented
gz-msgs 8.7.0 has been released so I deleted the branch from #349

2022-09-29 04:23 UTC, scpeters commented
@osrf-jenkins run tests please

2022-09-30 16:42 UTC, caguero reviewed
It looks good to me! My only concern is about the use of exceptions. I know that they have their advantages but the convention that we follow is to avoid them as much as possible and not to terminate the execution. Is there any chance we could avoid exceptions? Maybe return an error structure with extra information as opposed to a boolean for not loosing information?

2022-10-12 19:16 UTC, ivanpauno commented
> It looks good to me! My only concern is about the use of exceptions. I know that they have their advantages but the convention that we follow is to avoid them as much as possible and not to terminate the execution. Is there any chance we could avoid exceptions? Maybe return an error structure with extra information as opposed to a boolean for not loosing information?

Done, please take a look to the last few commits.

2022-10-12 20:08 UTC, scpeters commented
it looks like there are several test failures

2022-10-12 20:23 UTC, ivanpauno commented
> it looks like there are several test failures

Yes sorry, I'm figuring those out locally.

2022-10-12 21:35 UTC, scpeters commented on parameters/src/CMakeLists.txt
> +message(WARNING "ignition-utils${IGN_UTILS_VER}")
this line should be removed

2022-10-14 05:32 UTC, scpeters commented on parameters/include/ignition/transport/parameters/errors.hh
> +          private: std::string paramType;
there are two windows compiler warnings from these two lines

~~~
C:\Jenkins\workspace\ign_transport-pr-win\ws\gz-transport\parameters\include\ignition/transport/parameters/errors.hh(73,32): warning C4251: 'ignition::transport::parameters::v11::ParameterResult::paramName': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'ignition::transport::parameters::v11::ParameterResult' (compiling source file C:\Jenkins\workspace\ign_transport-pr-win\ws\gz-transport\parameters\src\errors.cc) [C:\Jenkins\workspace\ign_transport-pr-win\ws\build\ignition-transport11\parameters\src\ignition-transport11-parameters.vcxproj]

C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\VC\Tools\MSVC\14.29.30133\include\xstring(4905): message : see declaration of 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' (compiling source file C:\Jenkins\workspace\ign_transport-pr-win\ws\gz-transport\parameters\src\errors.cc) [C:\Jenkins\workspace\ign_transport-pr-win\ws\build\ignition-transport11\parameters\src\ignition-transport11-parameters.vcxproj]

C:\Jenkins\workspace\ign_transport-pr-win\ws\gz-transport\parameters\include\ignition/transport/parameters/errors.hh(74,32): warning C4251: 'ignition::transport::parameters::v11::ParameterResult::paramType': class 'std::basic_string<char,std::char_traits<char>,std::allocator<char>>' needs to have dll-interface to be used by clients of class 'ignition::transport::parameters::v11::ParameterResult' (compiling source file C:\Jenkins\workspace\ign_transport-pr-win\ws\gz-transport\parameters\src\errors.cc) [C:\Jenkins\workspace\ign_transport-pr-win\ws\build\ignition-transport11\parameters\src\ignition-transport11-parameters.vcxproj]
~~~

2022-10-14 13:05 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/errors.hh
> +          private: std::string paramType;
That's weird...
I think it can be solved if I move the methods definitions to the .cpp file, so I will try that.

2022-10-14 17:16 UTC, scpeters commented on parameters/include/ignition/transport/parameters/errors.hh
> +          private: std::string paramType;
we can suppress the warnings if they aren't easy to fix

2022-10-14 17:33 UTC, ivanpauno commented on parameters/include/ignition/transport/parameters/errors.hh
> +          private: std::string paramType;
solved

2022-10-14 23:25 UTC, scpeters commented
I think the ABI checker is a false positive, and the windows CI problems are from pre-existing protobuf compiler warnings

@caguero have all your concerns been addressed?

2022-10-25 19:44 UTC, caguero approved these changes
Looking good!

2022-10-26 17:21 UTC, merged