ign -> gz Namespace Migration : gz-transport
gazebosim/gz-transport pull request #311
Opened 2022-05-18 06:03 UTC by methylDragon

See https://github.com/gazebo-tooling/release-tools/issues/711

2022-05-18 17:02 UTC, chapulina reviewed
LGTM besides the 2 comments

2022-05-18 17:02 UTC, chapulina commented on include/ignition/transport/config.hh
> +namespace [[deprecated("Use gz namespace.")]]  ignition
As discussed, let's leave the warning commented out for now and when we enable it, we need to suppress the `-Wattributes` warning on GCC < 10

2022-05-19 22:47 UTC, methylDragon commented on include/ignition/transport/config.hh
> +namespace [[deprecated("Use gz namespace.")]]  ignition
Rectified with pragma deprecation https://github.com/gazebosim/gz-transport/pull/311/commits/2ee6c0c3fb461f49bc223e814bd21b23cb9b668c

2022-05-19 22:49 UTC, methylDragon commented on Migration.md
> +1. The `ignition` namespace is deprecated and will be removed in future versions.  Use `gz` instead.
1546644d8848fa3acec41cc4bebe146b755aa5c9

2022-05-20 02:04 UTC, chapulina approved these changes
LGTM with 🟢 CI

2022-05-25 01:08 UTC, chapulina requested changes

2022-05-25 01:08 UTC, chapulina commented on log/src/Log_TEST.cc
> +    testing::portablePathUnion(GZ_TRANSPORT_LOG_TEST_PATH, "data");
We need to tick-tock this env var

2022-05-25 01:08 UTC, chapulina commented on tutorials/20_env_variables.md
> +* **GZ_TRANSPORT_LOG_SQL_PATH**
I see you didn't migrate most env vars, only this one is migrated. How about reverting just this one so we tick-tock them all at once afterwards in a separate PR?

2022-05-25 01:08 UTC, chapulina commented on tutorials/21_contribute.md
> +See [Ignition's contribution guide](https://gazebosim.org/docs/all/contributing).
```suggestion
See [Gazebo's contribution guide](https://gazebosim.org/docs/all/contributing).
```

2022-05-25 06:03 UTC, methylDragon commented on log/src/Log_TEST.cc
> +    testing::portablePathUnion(GZ_TRANSPORT_LOG_TEST_PATH, "data");
I think this one doesn't need to, because it's a C++ variable defined in `test_config.h.in`, and is only used in this test

2022-05-25 06:05 UTC, methylDragon commented on tutorials/20_env_variables.md
> +* **GZ_TRANSPORT_LOG_SQL_PATH**
I tick-tocked it anyway just so there's an example implementation.

https://github.com/gazebosim/gz-transport/pull/311/commits/a5bfed899a07b9e9314f716f3b2da0aa2685a671

Also includes the Migration.md change

2022-05-26 20:58 UTC, chapulina commented on log/src/Log_TEST.cc
> +    testing::portablePathUnion(GZ_TRANSPORT_LOG_TEST_PATH, "data");
Ahh yeah false alarm!

2022-05-26 21:01 UTC, chapulina commented on tutorials/20_env_variables.md
> +* **GZ_TRANSPORT_LOG_SQL_PATH**
It looks like you're setting  the variable on tests, but the only variable that's used is still the `GZ` one:

https://github.com/gazebosim/gz-transport/blob/7887884ae36ca6de5d0185dfd9633cf3de50f338/log/include/gz/transport/log/Log.hh#L42

I think we can let the tests setting only the `GZ` one, but on the implementation we should also look at the `IGN` one, and print a warning if feasible.

2022-05-26 22:20 UTC, methylDragon commented on tutorials/20_env_variables.md
> +* **GZ_TRANSPORT_LOG_SQL_PATH**
https://github.com/gazebosim/gz-transport/pull/311/commits/e3daa00d9bc471b3c96feea16a40d768d29069d0

I'm gonna try to run a test build

2022-05-26 23:33 UTC, chapulina approved these changes
LGTM with 🟢  CI!

2022-05-29 01:06 UTC, merged