Bash completion for flags
gazebosim/gz-transport pull request #312
Opened 2022-05-20 03:28 UTC by mabelzhang

# 🎉 New feature

Part of https://github.com/gazebosim/gz-tools/issues/1
Used together with https://github.com/gazebosim/gz-tools/pull/87

## Summary

Bash completion, installation, tests.

This works with the installation method in the gz-tools PR described in this comment https://github.com/gazebosim/gz-tools/pull/87#discussion_r877692827 .

## Test it

```
. install/share/gz/gz.completion
ign service -<tab>
ign topic -<tab>
```

## Checklist
- [x] Signed all commits for DCO
- [x] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://ignitionrobotics.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://ignitionrobotics.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Aignitionrobotics+repo%3Aosrf%2Fsdformat+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2022-05-21 03:58 UTC, mabelzhang commented
Just realized there's also the `log` command. That's a bit different from the rest, as it has a third level of subcommands, `ign log record|playback`. It needs a different structure in the bash script, similar to `ign-tools/etc/ign.bash_completion.sh`.

In the interest of time, I think I will do all the two-level flags for as many library as possible first, for commands like `ign <subcommand> -<flag>`.

When we have more time, we can come back to the three-level flags, like `ign <subcommand> <subsubcommand> -<flag>`. So far, I can see that applies to `ign log` and `ign fuel`. There may be others.

2022-05-24 12:11 UTC, ahcorde requested changes

2022-05-24 12:11 UTC, ahcorde commented on src/cmd/transport.bash_completion.sh
> +#!/usr/bin/env bash
LICENSE ?

2022-05-24 12:11 UTC, ahcorde commented on src/cmd/transport.bash_completion.sh
> +    # NOTE: In Fortress+, remove --force-version and --versions. Add --help-all.
Instead of a NOTE. I think we should add a TODO and probably add this to the meta-ticket https://github.com/gazebosim/gz-tools/issues/1

2022-05-24 12:11 UTC, ahcorde commented on src/cmd/transport.bash_completion.sh
> +    # NOTE: In Fortress+, remove --force-version and --versions. Add
same here

2022-05-24 12:11 UTC, ahcorde commented on src/ign_TEST.cc
> +    "/src/cmd/transport.bash_completion.sh");
`ignition::common::joinPaths`

2022-05-24 12:11 UTC, ahcorde commented on src/ign_TEST.cc
> +  // NOTE: In Fortress+, remove --force-version and --versions. Add --help-all.
TODO here and below

2022-05-24 12:11 UTC, ahcorde commented on src/ign_TEST.cc
> +    "/src/cmd/transport.bash_completion.sh");
`ignition::common::joinPaths`

2022-06-03 04:52 UTC, mabelzhang commented on src/ign_TEST.cc
> +    "/src/cmd/transport.bash_completion.sh");
This is another package that doesn't depend on `gz-common` at all. I don't know if we should add it just for a test, comment out the test for certain OSes, or something else.

2022-06-03 04:52 UTC, mabelzhang commented on src/ign_TEST.cc
> +    "/src/cmd/transport.bash_completion.sh");
Same comment about dependency as above.

2022-06-03 07:14 UTC, mabelzhang commented on src/cmd/transport.bash_completion.sh
> +    # NOTE: In Fortress+, remove --force-version and --versions. Add --help-all.
Added to meta-ticket https://github.com/gazebosim/gz-tools/issues/1#issuecomment-1145661081

2022-06-03 07:44 UTC, ahcorde commented on src/ign_TEST.cc
> +    "/src/cmd/transport.bash_completion.sh");
maybe you can use `std::filesystem::path` ?

2022-06-03 22:57 UTC, mabelzhang commented on src/ign_TEST.cc
> +    "/src/cmd/transport.bash_completion.sh");
b54cd420

2022-06-03 22:57 UTC, mabelzhang commented on src/ign_TEST.cc
> +    "/src/cmd/transport.bash_completion.sh");
b54cd420

2022-06-07 14:51 UTC, ahcorde approved these changes

2022-06-14 22:58 UTC, chapulina approved these changes
Pushed some changes on b6c54300f1514dd0af7f20acdc6ff8d0c3cb24ba:

* Apply #249 to this branch, so it's on track with other libs
* Make sure we install CLI files even if `ign` isn't present
* Fix tests accordingly

2022-06-14 23:34 UTC, merged