ign -> gz Macro Migration : gz-transport
gazebosim/gz-transport pull request #319
Opened 2022-06-06 21:50 UTC by methylDragon

See: https://github.com/gazebo-tooling/release-tools/issues/737

2022-06-09 04:13 UTC, chapulina requested changes
Just 2 minor comments

2022-06-09 04:13 UTC, chapulina commented on include/ignition/transport/Helpers.hh
> +  #define GZ_ZMQ_POST_4_3_1 GZ_ZMQ_POST_4_3_1
```suggestion
  #define IGN_ZMQ_POST_4_3_1 GZ_ZMQ_POST_4_3_1
```

2022-06-09 04:13 UTC, chapulina commented on src/cmd/ign.hh
> +extern "C" const char GZ_DEPRECATED(12) *ignitionVersion();
No need to tick-tock, this isn't installed

2022-06-09 20:11 UTC, methylDragon commented on src/cmd/ign.hh
> +extern "C" const char GZ_DEPRECATED(12) *ignitionVersion();
https://github.com/gazebosim/gz-transport/pull/319/commits/3ea20c5946ee6d25084394f60b2a77a3ad8c52a3 !

2022-06-09 20:11 UTC, methylDragon commented on include/ignition/transport/Helpers.hh
> +  #define GZ_ZMQ_POST_4_3_1 GZ_ZMQ_POST_4_3_1
https://github.com/gazebosim/gz-transport/pull/319/commits/3ea20c5946ee6d25084394f60b2a77a3ad8c52a3 !

2022-06-15 15:27 UTC, chapulina approved these changes

2022-06-17 23:41 UTC, methylDragon commented
@osrf-jenkins run tests please!

2022-06-18 01:00 UTC, merged