ign -> gz Provisional Finale: Source Migration : gz-transport
gazebosim/gz-transport pull request #329
Opened 2022-07-14 01:43 UTC by methylDragon

See: https://github.com/gazebo-tooling/release-tools/issues/767

2022-07-14 18:56 UTC, chapulina requested changes

2022-07-14 18:56 UTC, chapulina commented on include/gz/transport/CIface.h
> +  using IgnTransportNode GZ_DEPRECATED(12) = GzTransportNode;  // TODO(CH3): Deprecated. Remove!
There's something here that Windows doesn't like

```
C:\Jenkins\workspace\ign_transport-pr-win\ws\ign-transport\include\gz/transport/CIface.h(34,26): error C2062: type 'int' unexpected (compiling source file C:\Jenkins\workspace\ign_transport-pr-win\ws\ign-transport\src\CIface.cc) 
```

2022-07-15 00:47 UTC, methylDragon commented on include/gz/transport/CIface.h
> +  using IgnTransportNode GZ_DEPRECATED(12) = GzTransportNode;  // TODO(CH3): Deprecated. Remove!
I'm pretty sure it's the `GZ_DEPRECATED` macro call...

I couldn't get it to compile putting it anywhere else, but I guess windows doesn't like it even there.
Are you alright with removing it?

2022-07-21 22:42 UTC, methylDragon commented on include/gz/transport/CIface.h
> +  using IgnTransportNode GZ_DEPRECATED(12) = GzTransportNode;  // TODO(CH3): Deprecated. Remove!
https://github.com/gazebosim/gz-transport/pull/329/commits/350ecf04f8c2aa7e38256cb7fe6902c81d506d44 fixed like the rest

2022-07-22 19:00 UTC, chapulina approved these changes

2022-07-23 04:23 UTC, chapulina commented
The failures aren't caused by this PR and are being addressed in https://github.com/gazebosim/gz-transport/pull/335.

2022-07-23 04:23 UTC, merged