Python Bindings for Publisher, Subscriber and Requester features.
gazebosim/gz-transport pull request #411
Opened 2023-06-20 22:52 UTC by Voldivh

# 🎉 New feature

Closes #387 

## Summary

This PR creates the python bindings for the publisher, subscriber and request features from the repository. In order to avoid creating a new dependency to be able to create python bindings from protobuf messages, it was decided to use the methods that publishes, subscribes and make services request with serialized messages, i.e, use the methods `PublishRaw`, `SubscribeRaw` and `RequestRaw`. The bindings for these methods are wrapped by python methods  in order to give the user an API similar to the one we have in C++.

## Test it

There are some [examples](https://github.com/Voldivh/gz-transport/tree/voldivh/pybind11_bindings/python/examples) that were created as smoke test in order to test out the functionality. In order to use them you would have to:

1. Compile from source this branch
2. Update the `PYTHONPATH` variable:
```bash
export PYTHONPATH=$PYTHONPATH:<path_to_ws>/install/lib/python
```
3. Run the python script for the example you would like to try out:
```bash
python3 <path_to_ws>/src/gz-transport/python/examples/<example_to_run>
```
**Note**: The service requester example will only work if there is a server running that listens to `/echo` topic and expects a `gz.messages.StringMsg` as the request. One way to do so is to follow the instructions on the [examples folder](https://github.com/Voldivh/gz-transport/blob/voldivh/pybind11_bindings/example/README.md) and run the `responser` executable.

2023-06-21 07:51 UTC, ahcorde requested changes

2023-06-21 07:51 UTC, ahcorde commented on python/CMakeLists.txt
> +    message("")
remove

2023-06-21 07:51 UTC, ahcorde commented on CMakeLists.txt
> -
discard change

2023-06-21 07:51 UTC, ahcorde commented on python/CMakeLists.txt
> +
```suggestion
```

2023-06-21 07:51 UTC, ahcorde commented on python/examples/publisher.py
> +from gz.msgs10.stringmsg_pb2 import StringMsg
LICENSE

2023-06-21 07:51 UTC, ahcorde commented on python/examples/publisher.py
> +          #  print("Publishing 'Hello' on topic [{}]".format(stringmsg_topic))
remove?

2023-06-21 07:51 UTC, ahcorde commented on python/examples/requester.py
> +from gz.msgs10.stringmsg_pb2 import StringMsg
LICENSE

2023-06-21 07:51 UTC, ahcorde commented on python/examples/subscriber.py
> +from gz.msgs10.stringmsg_pb2 import StringMsg
LICENSE

2023-06-21 07:51 UTC, ahcorde commented on python/src/__init__.py
> +from ._transport import Node as _Node
LICENSE

2023-06-21 07:51 UTC, ahcorde commented on python/src/transport/_gz_transport_pybind11.cc
> + * Copyright (C) 2015 Open Source Robotics Foundation
```suggestion
 * Copyright (C) 2023 Open Source Robotics Foundation
```

2023-06-21 07:51 UTC, ahcorde commented on python/src/transport/_gz_transport_pybind11.cc
> +#include <pybind11/stl.h>
alphabetize

2023-06-21 07:51 UTC, ahcorde commented on python/src/transport/_gz_transport_pybind11.cc
> +      ;
`;` are in a weird location

2023-06-21 07:51 UTC, ahcorde commented on python/test/requester_TEST.py
> +from gz.msgs10.stringmsg_pb2 import StringMsg
LICENSE

2023-06-22 18:51 UTC, Voldivh commented on python/CMakeLists.txt
> +    message("")
Do you mean the `message("")` or the whole `if-else` statement?

2023-06-22 19:24 UTC, Voldivh commented on python/test/requester_TEST.py
> +from gz.msgs10.stringmsg_pb2 import StringMsg
Done.

2023-06-22 19:24 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +      ;
Done.

2023-06-22 19:25 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> + * Copyright (C) 2015 Open Source Robotics Foundation
Done.

2023-06-22 19:25 UTC, Voldivh commented on python/src/__init__.py
> +from ._transport import Node as _Node
Done.

2023-06-22 19:25 UTC, Voldivh commented on python/examples/requester.py
> +from gz.msgs10.stringmsg_pb2 import StringMsg
Done.

2023-06-22 19:25 UTC, Voldivh commented on python/examples/publisher.py
> +          #  print("Publishing 'Hello' on topic [{}]".format(stringmsg_topic))
Done.

2023-06-22 19:25 UTC, Voldivh commented on python/examples/publisher.py
> +from gz.msgs10.stringmsg_pb2 import StringMsg
Done.

2023-06-22 19:25 UTC, Voldivh commented on python/CMakeLists.txt
> +
Done.

2023-06-22 19:25 UTC, Voldivh commented on CMakeLists.txt
> -
Done.

2023-06-23 07:51 UTC, ahcorde requested changes

2023-06-23 07:51 UTC, ahcorde commented on python/examples/subscriber.py
> +    # TODO(azeey) The subscriber if we quit without unsubscribing. This may not
This PR is in, remove TODO or fix this

2023-06-23 07:51 UTC, ahcorde commented on python/src/__init__.py
> +# Copyright (C) 2015 Open Source Robotics Foundation
```suggestion
# Copyright (C) 2023 Open Source Robotics Foundation
```

2023-06-23 20:41 UTC, Voldivh commented on python/examples/subscriber.py
> +    # TODO(azeey) The subscriber if we quit without unsubscribing. This may not
Done.

2023-06-23 20:41 UTC, Voldivh commented on python/src/__init__.py
> +# Copyright (C) 2015 Open Source Robotics Foundation
Done.

2023-06-23 22:30 UTC, azeey requested changes
Looks great overall. Most of the comments should be easy to address. Some 
comments might be addressed in a follow-up PR.

2023-06-23 22:30 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +      .def("advertised_services", &Node::AdvertisedServices,
Since we don't support advertizing services, this can be removed.

2023-06-23 22:30 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +      .def("request_raw", [](
It's easier to check if there's parity between the C++ class and the python 
bindings if the member functions come in the order they're defined in the C++ 
class. Can you move `request_raw` to come before `topic_list`? Same with `subscribe_raw`.

2023-06-23 22:30 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +          std::string &_response)
As I mentioned in a previous comment, we can drop the `_response` argument. 
I don't think we want to be mutating a reference anyway in pybind11. Instead, we'd 
create the response object on the stack here.

2023-06-23 22:30 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +            return std::make_tuple(result, py::bytes(_response.c_str(), _response.size()));
I wonder if it's better to return with `py::make_tuple` instead.

2023-06-23 22:30 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +            return std::make_tuple(result, py::bytes(_response.c_str(), _response.size()));
I wonder if it's better to return with `py::make_tuple` instead?

2023-06-23 22:30 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +            return std::make_pair(publishers, subscribers);
I wonder if it's better to return with `py::make_tuple` instead?

2023-06-23 22:30 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +      .def(py::init<>())
This might be a follow up PR, but can you add the constructor that takes `NodeOptions`?

2023-06-23 22:30 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +          "Get the information about a service");
There are a few more member functions, `Options`, `EnableStats`, and `TopicStats`. Can you add bindings for them?

2023-06-23 22:30 UTC, azeey commented on python/test/pubSub_TEST.py
> +        self.pub_node = Node()
Usually we put things in `setUp` things that are common to all the tests in 
this test case. If that's the intention, ignore this, otherwise, I recommend 
putting most of this code in `test_msg_callback`.

2023-06-23 22:30 UTC, azeey commented on python/test/pubSub_TEST.py
> +        self.assertTrue(self.pub_node)
Not sure what this is asserting

2023-06-23 22:30 UTC, azeey commented on python/test/pubSub_TEST.py
> +        self.assertTrue(self.sub_node.subscribe(Vector3d, vector3d_topic, self.vector3_cb))
Not sure what this is asserting

2023-06-23 22:30 UTC, azeey commented on python/test/pubSub_TEST.py
> +        self.assertEqual(self.received_msg, self.vector3d_msg.x)
I wonder if we need to wait for the publisher to actually publish.

This also 
makes me think about data races. But reading the [pybind11 documentation](https://pybind11.readthedocs.io/en/stable/advanced/misc.html#global-interpreter-lock-gil), it 
looks like the GIL will be locked before calling the callback.

2023-06-23 22:30 UTC, azeey commented on python/test/requester_TEST.py
> +        os.environ['GZ_PARTITION'] = gz_partition
Do we need to reset the partition after the test is done to avoid affecting 
other tests?

2023-06-23 22:30 UTC, azeey commented on python/test/requester_TEST.py
> +        gz_partition = 'python_requester_test'
I don't think using `setUp` and `tearDown` makes sense if we have just one 
test.

2023-06-23 22:30 UTC, azeey commented on python/test/requester_TEST.py
> +        self.assertTrue(self.node)
Remove?

2023-06-23 22:30 UTC, azeey commented on python/test/pubSub_TEST.py
> +class pubSubTEST(unittest.TestCase):
Class names should start with an uppercase letter according to [PEP8](https://peps.python.org/pep-0008/#class-names).

2023-06-23 22:30 UTC, azeey commented on python/test/requester_TEST.py
> +class requesterTEST(unittest.TestCase):
Class names should start with an uppercase letter according to [PEP8](https://peps.python.org/pep-0008/#class-names).

2023-06-23 22:30 UTC, azeey commented on python/test/requester_TEST.py
> +        result, response = self.node.request(self.service_name, self.request, Int32, Int32, self.timeout, self.response)
This line is too long. Can you reformat?

2023-06-26 14:51 UTC, Voldivh commented on python/CMakeLists.txt
> +# Deal with naming collision on Windows. It is caused by the both the import
I'm not completely sure what to do on this one. Should I modify the current `ARCHIVE_OUTPUT_NAME` to something like the following and remove the comment?
```CMake
set_target_properties(${BINDINGS_MODULE_NAME} PROPERTIES
  ARCHIVE_OUTPUT_NAME "_transport${PROJECT_VERSION_MAJOR}")
```

2023-06-26 15:15 UTC, Voldivh commented on python/src/__init__.py
> +                                response_type.DESCRIPTOR.full_name, timeout, response.SerializeToString())
Yeah, I actually thought the same. We can certainly remove that argument.

2023-06-26 15:40 UTC, Voldivh commented on CMakeLists.txt
> +if (NOT PYTHON3_FOUND)
Done.

2023-06-26 15:40 UTC, Voldivh commented on python/CMakeLists.txt
> +set(BINDINGS_MODULE_NAME "_transport")
Sure and done.

2023-06-26 15:40 UTC, Voldivh commented on python/CMakeLists.txt
> +# library are called sdformat13.lib.
Nice catch. Done.

2023-06-26 15:40 UTC, Voldivh commented on python/src/__init__.py
> +        result, serialized_response = self.request_raw(service, request.SerializeToString(), request_type.DESCRIPTOR.full_name,
Done.

2023-06-26 15:40 UTC, Voldivh commented on python/src/__init__.py
> +                                response_type.DESCRIPTOR.full_name, timeout, response.SerializeToString())
Done.

2023-06-26 15:48 UTC, Voldivh commented on python/src/__init__.py
> +    def publish(self, proto_msg):
Sure, QQ: For the protobuf message arguments what did we agreed to use? Create a TypeVar like 
```python
from typing import TypeVar
ProtoMsgType = TypeVar('ProtoMsgType')
```

2023-06-26 15:51 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +      .def("subscribe", [](
Done.

2023-06-26 17:27 UTC, Voldivh commented on python/test/pubSub_TEST.py
> +        self.pub_node = Node()
Yeah, my idea was to create things needed in all the test cases there. More test will come to this files so I'll take this comment into account when I'm adding them.

2023-06-26 17:33 UTC, Voldivh commented on python/test/requester_TEST.py
> +        os.environ['GZ_PARTITION'] = gz_partition
From what I saw, the other test set this environment variable at their setup. I could be wrong about this since I didn't look at all the test and the `requester_TEST` is the last one to run. I'll take a closer look.

2023-06-26 17:34 UTC, Voldivh commented on python/test/requester_TEST.py
> +        gz_partition = 'python_requester_test'
I used the methods taking into account that more test will be incoming to the python test files. I'll take this comment into account when doing that.

2023-06-26 18:03 UTC, Voldivh commented on python/CMakeLists.txt
> +# Deal with naming collision on Windows. It is caused by the both the import
Done.

2023-06-26 18:04 UTC, Voldivh commented on python/src/__init__.py
> +    def publish(self, proto_msg):
Done.

2023-06-26 18:04 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +          "The scope used in this topic/service");
Done.

2023-06-26 18:04 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +    py::class_<MessageInfo>(
Sure and done.

2023-06-26 18:04 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +      .def("request_raw", [](
Done for `request_raw`, however, I'm not sure what to do with `subscribe_raw` it already comes before `topic_list` and `request_raw`

2023-06-26 18:04 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +            return std::make_tuple(result, py::bytes(_response.c_str(), _response.size()));
Done.

2023-06-26 18:04 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +            return std::make_pair(publishers, subscribers);
Done.

2023-06-26 18:04 UTC, Voldivh commented on python/test/requester_TEST.py
> +class requesterTEST(unittest.TestCase):
Done.

2023-06-26 20:07 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +          std::function<void(py::bytes _msgData, const size_t _size,
I think I don't completely understand this one. In order to create the method callback on the lambda method, we need the size of the message is there a way to get that information from the object that `py::bytes` return? I tried looking it up but I couldn't find much.

2023-06-26 20:12 UTC, Voldivh commented on python/test/pubSub_TEST.py
> +        self.assertTrue(self.pub_node)
I noticed on the current C++ test some assertions on the node creation. I was just replicating the same behavior on python. If for some reason we are unable to create the node with the bindings the assertion would fail. Let me know if you think we should remove this.

2023-06-26 20:13 UTC, Voldivh commented on python/test/pubSub_TEST.py
> +        self.assertTrue(self.sub_node.subscribe(Vector3d, vector3d_topic, self.vector3_cb))
Same comment here as in https://github.com/gazebosim/gz-transport/pull/411#discussion_r1242714434. Same logic for verifying that the subscription was created.

2023-06-26 20:13 UTC, Voldivh commented on python/test/requester_TEST.py
> +        self.assertTrue(self.node)
Same comment as in https://github.com/gazebosim/gz-transport/pull/411#discussion_r1242714434

2023-06-27 03:37 UTC, azeey commented
This requires https://github.com/gazebosim/gz-msgs/pull/355.

2023-06-27 16:30 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +      .def(py::init<>())
Done. I also created the bindings for the `NodeOptions` class

2023-06-27 16:42 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +          "Get the information about a service");
Done.

2023-06-27 22:27 UTC, azeey commented on python/src/__init__.py
> +        def cb_deserialize(proto_msg, msg_size, msg_info):
`msg_size` is not used here, so it can be removed. This what I meant in my other comment.

2023-06-27 22:27 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +          std::function<void(py::bytes _msgData, const size_t _size,
I left a comment in the python callback. The size is not used there so we can 
remove it from the callback signature here and in the python code.

2023-06-27 22:27 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +          py::arg("toTopic"),
nit: I think argument names also use the snake_case style.

2023-06-27 22:27 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +          NodeOptions &_nodeOptions,
```suggestion
          NodeOptions &self,
```

2023-06-27 22:27 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +      .def("request_raw", [](
I meant the same principle of synced order between C++ and python applied to 
`subscribe_raw`. Looks like it is good now.

2023-06-27 22:27 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +          py::arg("publicationTopic"),
The C++ version has default arguments. Can you do the same here?

2023-06-27 22:27 UTC, azeey commented on python/test/pubSub_TEST.py
> +        self.assertTrue(self.pub_node)
Can you point me to the C++ test you're referring to. I believe the only way 
the constructor would fail is if it throws an exception and if it does throw an 
exception, the code wouldn't get to this line.

2023-06-27 22:27 UTC, azeey commented on python/test/requester_TEST.py
> +        os.environ['GZ_PARTITION'] = gz_partition
Okay, since other tests will be running in different processes, it's probably 
okay.

2023-06-27 23:29 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +      .def("request_raw", [](
I assumed later what you meant by taking a look to the `Node.hpp` file.

2023-06-27 23:41 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +          std::function<void(py::bytes _msgData, const size_t _size,
I think I didn't explain myself appropriately. I meant that we need the size of the data in order to generate the `gz::transport::RawCallback` used by the `SubscribeRaw`. At this moment I'm implicitly using the data size retrieved by the callback on python in order to be able to create that. If I remove it from the signature I would need to get the size of the message from another place in order to create that `RawCallback`. I'm not sure if it makes sense to create an object on the lambda method (C++ bindings side) and get the size of that object as the other argument. Something like:
```C++
.def("subscribe_raw", [](
          Node &_node,
          const std::string &_topic,
          std::function<void(py::bytes _msgData,
                           const MessageInfo &_info)> &_callback,
          const std::string &_msgType,
          const SubscribeOptions &_opts)
          {
            auto _cb = [_callback](const char *_msgData,
                           const MessageInfo &_info){
                auto data_object = py::bytes(_msgData);
                return _callback(data_object, sizeof(data_object_size), _info);
            };
            return _node.SubscribeRaw(_topic, _cb, _msgType, _opts);
          },
```

2023-06-27 23:54 UTC, Voldivh commented on python/test/pubSub_TEST.py
> +        self.assertTrue(self.pub_node)
You are right. I took a quick look [here](https://github.com/Voldivh/gz-transport/blob/57561475bc2301b33ff4d503bb820693171e1caa/test/integration/twoProcsPubSub.cc#L107) and thought it was asserting the node creation but it is assertion that the method worked. I'll remove those assertions here and there.

2023-06-28 16:02 UTC, Voldivh commented on python/src/__init__.py
> +    def publish(self, proto_msg):
Sure. Done.

2023-06-28 16:02 UTC, Voldivh commented on python/src/__init__.py
> +    def publish(self, proto_msg: ProtoMsg):
Sure.

2023-06-28 16:03 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +          py::arg("toTopic"),
Yep, you are right. Done.

2023-06-28 16:03 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> +          py::arg("publicationTopic"),
Yep, done.

2023-06-28 16:14 UTC, srmainwaring commented on python/src/transport/_gz_transport_pybind11.cc
> + * Copyright (C) 2015 Open Source Robotics Foundation
Could you pls retain the `Copyright (C) 2022 Rhys Mainwaring` line from https://github.com/srmainwaring/gz-python/blob/main/src/pybind11/gz/transport/_gz_transport_pybind11.cc as this is based on that version.

2023-06-28 21:50 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> + * Copyright (C) 2015 Open Source Robotics Foundation
Sure I don't see any problem. Wdyt @ahcorde?

2023-06-29 16:51 UTC, Voldivh commented on python/src/__init__.py
> +    def publish(self, proto_msg: ProtoMsg):
Done.

2023-07-01 20:48 UTC, srmainwaring commented on python/src/transport/_gz_transport_pybind11.cc
> + * Copyright (C) 2015 Open Source Robotics Foundation
Thanks for adding @Voldivh - I actually meant for you to add the original note below the line for OSRF (i.e. two lines - one below for the original work and another above for the derived work - I think that's the usual practice.)

Btw - nice job, this is looking v. good. I'll try to test and give feedback against some of the examples I have.

2023-07-03 23:26 UTC, Voldivh commented on python/src/transport/_gz_transport_pybind11.cc
> + * Copyright (C) 2015 Open Source Robotics Foundation
@srmainwaring Done (I think :D). If you manage to have some time to test it out it would be really helpful.

2023-07-05 17:43 UTC, Voldivh commented
Added the python version example of https://github.com/gazebosim/gz-sim/tree/main/examples/standalone/multi_lrauv_race in https://github.com/gazebosim/gz-transport/pull/411/commits/2f23947262eb71c4b43c6e16705fc5565ee5f2ad using the bindings created on this PR. In order to run it follow the next steps, this takes into account that you have Gazebo installed and `gz-transport` package compiled:
1. Launch the world (This would require to have the source code of gz-sim on the `main` branch):
```bash
gz sim -r <path_to_ws>/src/gz-sim/examples/worlds/multi_lrauv_race.sdf
```
2. Update the `PYTHONPATH` variable:
```bash
export PYTHONPATH=$PYTHONPATH:<path_to_ws>/install/lib/python
```
3. Run the python script for the example:
```bash
python3 <path_to_ws>/src/gz-transport/python/examples/multi_lrauv_race.py
```

2023-07-10 14:35 UTC, Voldivh commented on python/src/__init__.py
> +        def cb_deserialize(proto_msg, msg_size, msg_info):
Done.

2023-07-10 22:39 UTC, azeey approved these changes
Just a few more minor comments. Otherwise, LGTM!

Would you be able to merge from main and update this to use https://github.com/gazebosim/gz-msgs/pull/355?

2023-07-10 22:39 UTC, azeey commented on python/examples/multi_lrauv_race.py
> +#   $ python3 multi_lrauv_race
```suggestion
#   $ python3 multi_lrauv_race.py
```

2023-07-10 22:39 UTC, azeey commented on python/src/__init__.py
> +    def publish(self, proto_msg):
Nice explanation! Thanks.

2023-07-10 22:39 UTC, azeey commented on python/src/transport/_gz_transport_pybind11.cc
> +          py::arg("toTopic"),
Can you also update the docstring?

2023-07-10 22:39 UTC, azeey commented on python/test/options_TEST.py
> +class PubSubTEST(unittest.TestCase):
Should this be renamed?

2023-07-10 22:39 UTC, azeey commented on python/test/pubSub_TEST.py
> +        self.assertEqual(topic_stats, None)
Should `topic_stats` be `None`? I would have expected it to have some value.

2023-07-11 16:47 UTC, Voldivh commented on python/test/pubSub_TEST.py
> +        self.assertEqual(topic_stats, None)
I thought the same, however, take a look at the [C++ test version](https://github.com/gazebosim/gz-transport/blob/9147781be37d0ccafc1dcff741e94c9deec1d937/test/integration/statistics.cc#L71).

2023-07-14 16:24 UTC, azeey reviewed
I have one test failure. Not sure if it's failing for you. Also, I know I asked 
you to rebase this to work with new message generation framework in `gz-msgs`. 
But since that's been reverted, could you also revert the change here? I plan 
to open a gz-msgs PR that uses the old message generation framework and adds 
python bindings.

2023-07-14 16:24 UTC, azeey commented on python/test/options_TEST.py
> +class PubSubTEST(unittest.TestCase):
`OptionsTEST`?

2023-07-14 16:24 UTC, azeey commented on python/test/pubSub_TEST.py
> +        self.assertEqual(len(topics), 2)
This is failing for me locally with 
```
103:         self.assertTrue(topics)
103: >       self.assertEqual(len(topics), 2)
103: E       AssertionError: 12 != 2
```

2023-07-14 16:24 UTC, azeey commented on python/test/pubSub_TEST.py
> +        self.assertEqual(topic_stats, None)
Ah, okay. Mind adding a comment similar to the C++ version?

2023-07-14 17:22 UTC, Voldivh commented on python/test/options_TEST.py
> +class PubSubTEST(unittest.TestCase):
Oh, I was mistaken on the file when I read the comment, my bad. Yeah that makes a lot of sense.

2023-07-14 17:24 UTC, Voldivh commented on python/test/pubSub_TEST.py
> +        self.assertEqual(len(topics), 2)
Hmmm I'm not getting that assertion error. When I modified the msg generation framework, some test started failing (not only on python). I'll take a look after reverting that change.

2023-07-14 17:24 UTC, Voldivh commented on python/test/pubSub_TEST.py
> +        self.assertEqual(topic_stats, None)
Sure, will do.

2023-07-14 17:25 UTC, Voldivh commented
> I have one test failure. Not sure if it's failing for you. Also, I know I asked you to rebase this to work with new message generation framework in `gz-msgs`. But since that's been reverted, could you also revert the change here? I plan to open a gz-msgs PR that uses the old message generation framework and adds python bindings.

No problem, just one question then, should I change this PR to target the `main` as before then?

2023-07-14 18:26 UTC, azeey commented
> > I have one test failure. Not sure if it's failing for you. Also, I know I asked you to rebase this to work with new message generation framework in `gz-msgs`. But since that's been reverted, could you also revert the change here? I plan to open a gz-msgs PR that uses the old message generation framework and adds python bindings.
> 
> No problem, just one question then, should I change this PR to target the `main` branch as before then?

Yes, target the `main` branch.

2023-07-18 02:19 UTC, azeey commented
@osrf-jenkins run tests please

2023-07-18 23:14 UTC, azeey commented
Needs https://github.com/gazebo-release/gz-msgs10-release/pull/6 for CI.

2023-07-19 21:27 UTC, azeey commented
I've built gz-msgs10 debians just for Jammy for testing and added a new dependency in https://github.com/gazebosim/gz-transport/pull/411/commits/e1bca5ec9b41c9569618fc83317c9a6f188e9102. It looks like tests are passing on Jenkins 🎉

2023-07-19 21:39 UTC, azeey commented on python/CMakeLists.txt
> +    list(APPEND _env_vars "PYTHONPATH=${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/python/:${CMAKE_BINARY_DIR}/lib:$ENV{PYTHONPATH}")
I think the Github Actions job is failing because the tests are running without install, i.e, just `make` and `make test`. To make that work, we need change the resulting directory structure. Right now, we have
```
.
|-- bin
|-- cmake
|-- lib
|   |-- _transport.cpython-310-x86_64-linux-gnu.so
|-- test_results
`-- tutorials.md
```

But I think we want
```
.
|-- bin
|-- cmake
|-- lib
|   |-- gz
|   |   |-- transport13
|   |   |   |-- __init__.py
|   |   |   |-- _transport.cpython-310-x86_64-linux-gnu.so
|-- test_results
`-- tutorials.md
 ```

2023-07-19 21:42 UTC, azeey commented on python/CMakeLists.txt
> +    list(APPEND _env_vars "PYTHONPATH=${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/python/:${CMAKE_BINARY_DIR}/lib:$ENV{PYTHONPATH}")
I'm not sure how we can do that exactly. The alternative, and the quicker way is to add a `.github/ci/after_make.sh` similar to https://github.com/azeey/gz-msgs/blob/9b14d178c6673ef9b56c959b52868e54cc1199fe/.github/ci/after_make.sh.

2023-07-20 15:14 UTC, Voldivh commented on python/CMakeLists.txt
> +    list(APPEND _env_vars "PYTHONPATH=${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/python/:${CMAKE_BINARY_DIR}/lib:$ENV{PYTHONPATH}")
I added it on https://github.com/gazebosim/gz-transport/pull/411/commits/3bfb36500c71cb43ae2d46368d1903e0641f767d, however, CI is still failing. I noticed an error that it was not able to find `python3-gz-msgs10` package.

2023-07-20 21:33 UTC, azeey commented
https://github.com/gazebo-release/gz-msgs10-release/pull/6 is merged and I've built the debs for Focal and Jammy, so I'll run tests again.

@osrf-jenkins run tests please

2023-07-20 23:26 UTC, azeey commented
@osrf-jenkins run tests please

2023-07-21 05:39 UTC, azeey commented on python/CMakeLists.txt
> +    list(APPEND _env_vars "PYTHONPATH=${CMAKE_INSTALL_PREFIX}/${CMAKE_INSTALL_LIBDIR}/python/:${CMAKE_BINARY_DIR}/lib:$ENV{PYTHONPATH}")
I've resolved the packaging issue, but there was a type in the name of the `after_make.sh` file (fixed inhttps://github.com/gazebosim/gz-transport/pull/411/commits/5371b41adbb8af9d36ab30c77db1e796a0551b82). Now all CI is passing!!

2023-07-21 17:10 UTC, azeey commented on python/test/pubSub_TEST.py
> +        self.assertEqual(len(topics), 2)
Okay, this is no longer failing for me. Probably something wrong with my local setup last time I tried.

2023-07-21 17:11 UTC, azeey approved these changes
@ahcorde All your feedback has been resolved. Do you want to take another look?

2023-07-24 17:05 UTC, ahcorde approved these changes

2023-07-24 17:32 UTC, merged