Adds the python bindings tutorial
gazebosim/gz-transport pull request #450
Opened 2023-10-03 17:45 UTC by Voldivh

# 🎉 New feature

## Summary
This PR creates a new tutorial page with all the relevant information regarding the python API created for gz-transport in https://github.com/gazebosim/gz-transport/pull/411.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2023-10-03 19:58 UTC, mjcarroll commented on python/examples/publisher.py
> +          if not (pub_stringmsg.publish(stringmsg_msg)):
I think you can drop the parens now that there is a single condition.

2023-10-03 19:58 UTC, mjcarroll commented on python/examples/publisher.py
> +          if not (pub_vector3d.publish(vector3d_msg)):
Same here

2023-10-03 19:58 UTC, mjcarroll commented on tutorials/01_intro.md
> +C++ is the native implementation and the only language that have available all library features.
```suggestion
C++ is the native implementation and the only language that has all available library features.
```

2023-10-03 19:58 UTC, mjcarroll commented on tutorials/06_python_support.md
> +For this tutorial, we will create two nodes that are going to communicate via messages. One node will be a publisher that generates the information,
```suggestion
For this tutorial, we will create two nodes that communicate via messages. One node will be a publisher that generates the information,
```

2023-10-03 20:14 UTC, ahcorde requested changes

2023-10-03 20:14 UTC, ahcorde commented on tutorials/06_python_support.md
> +In this tutorial, we are going to show the functionalities implemented in python. This features are brought up to python by creating bindings from the C++ implementation using pybind11. It is importa
shorten lines 
```suggestion
In this tutorial, we are going to show the functionalities implemented in python. This features are brought up to python by creating bindings from the C++ implementation using pybind11. It is important to note that not all of C++ features are available yet in Python, on this tutorial we will go over the most relevant features we currently have on Python. For more information refer to the [__init__.py](https://github.com/gazebosim/gz-transport/blob/gz-transport13/python/src/__init__.py) file which is a wrapper for all the bindings.
```

2023-10-03 20:14 UTC, ahcorde commented on tutorials/06_python_support.md
> +The library `gz.transport13` contains all the Gazebo Transport elements that can be used in python. The final API we will use is contained inside the class `Node`.
```suggestion
The library `gz.transport13` contains all the Gazebo Transport elements that can be used in Python. The final API we will use is contained inside the class `Node`.
```

2023-10-03 20:14 UTC, ahcorde commented on tutorials/06_python_support.md
> +the first step is to announce our topics names and their  types. Once a topic name is
```suggestion
the first step is to announce our topics names and their types. Once a topic name is
```

2023-10-03 20:14 UTC, ahcorde commented on tutorials/06_python_support.md
> +a new topic update. The signature of the callback is always similar to the ones
```suggestion

We need to register a function callback that will execute every time we receive
a new topic update. The signature of the callback is always similar to the ones
```

2023-10-03 20:14 UTC, ahcorde commented on tutorials/06_python_support.md
> +If you made the binary installation of Gazebo Transport, you can skip this step and go directly to the next section. Otherwise, if you built the package from source it is needed to update the PYTHONP
```suggestion
If you made the binary installation of Gazebo Transport, you can skip this step and go directly to the next section. Otherwise, if you built the package from source it is needed to update the PYTHONPATH in order for Python to recognize the library by doing the following:
```

2023-10-03 20:14 UTC, ahcorde commented on tutorials/06_python_support.md
> +or
```suggestion

or
```

2023-10-03 20:14 UTC, ahcorde commented on tutorials/06_python_support.md
> +## Subscribe Options
```suggestion
as an argument to the *advertise()* method.

## Subscribe Options
```

2023-10-04 15:13 UTC, Voldivh commented on python/examples/publisher.py
> +          if not (pub_vector3d.publish(vector3d_msg)):
Done.

2023-10-04 15:13 UTC, Voldivh commented on tutorials/01_intro.md
> +C++ is the native implementation and the only language that have available all library features.
Done.

2023-10-04 15:13 UTC, Voldivh commented on tutorials/01_intro.md
> +Python implementation is a wrapper around C++ methods using pybind11. It does not support all features like C++, but, contains the main features such as publication, subscription and service request.
Done.

2023-10-04 15:13 UTC, Voldivh commented on tutorials/06_python_support.md
> +For this tutorial, we will create two nodes that are going to communicate via messages. One node will be a publisher that generates the information,
Thanks and done.

2023-10-04 15:13 UTC, Voldivh commented on tutorials/06_python_support.md
> +In this tutorial, we are going to show the functionalities implemented in python. This features are brought up to python by creating bindings from the C++ implementation using pybind11. It is importa
Done.

2023-10-04 15:13 UTC, Voldivh commented on tutorials/06_python_support.md
> +The library `gz.transport13` contains all the Gazebo Transport elements that can be used in python. The final API we will use is contained inside the class `Node`.
Done.

2023-10-04 15:13 UTC, Voldivh commented on tutorials/06_python_support.md
> +the first step is to announce our topics names and their  types. Once a topic name is
Done.

2023-10-04 15:13 UTC, Voldivh commented on tutorials/06_python_support.md
> +a new topic update. The signature of the callback is always similar to the ones
Done.

2023-10-04 15:14 UTC, Voldivh commented on tutorials/06_python_support.md
> +If you made the binary installation of Gazebo Transport, you can skip this step and go directly to the next section. Otherwise, if you built the package from source it is needed to update the PYTHONP
Done.

2023-10-04 15:14 UTC, Voldivh commented on tutorials/06_python_support.md
> +or
Done.

2023-10-04 15:14 UTC, Voldivh commented on tutorials/06_python_support.md
> +## Subscribe Options
Done.

2023-10-05 16:09 UTC, ahcorde requested changes
you have some errors in CI https://github.com/gazebosim/gz-transport/actions/runs/6408005204/job/17396035440?pr=450

2023-10-16 12:54 UTC, ahcorde commented
friendly ping @Voldivh

2023-10-16 13:05 UTC, ahcorde commented
@Voldivh there are still some unresolved comments

2023-10-16 14:57 UTC, ahcorde requested changes

2023-10-16 14:57 UTC, ahcorde commented on tutorials/06_python_support.md
> +Open two new terminals and directly run the python scripts downloaded previously.
still pending

2023-10-16 14:57 UTC, ahcorde commented on tutorials/06_python_support.md
> +The way Gazebo Transport is implemented, it creates several threads each time a node, publisher, subscriber, etc is created. While this allows us to have a better paralization in processes, a downsid
```suggestion
The way Gazebo Transport is implemented, it creates several threads each time a node, publisher, subscriber, etc is created. While this allows us to have a better paralization in processes, a downside is possible race conditions that might occur if the ownership/access of variables is shared across multiple processes. Even though Python have it's [GIL](https://wiki.python.org/moin/GlobalInterpreterLock), all the available features are bindings created for it's C++ implementation, in other words, downsides commented before are still an issue to be careful. We recommend to always use threading locks when working with object that are used in several places (publisher and subscribers). 
```

2023-10-16 14:57 UTC, ahcorde commented on tutorials/06_python_support.md
> +Unfortunately, this feature is not available on python at the moment. However, we can use a service responser created in C++ and make a request to it from a code in python. Taking that into account,
still pending

2023-10-16 14:57 UTC, ahcorde commented on tutorials/06_python_support.md
> +Open a new terminal and directly run the python script downloaded previously. It is expected that the service responser is running in another terminal for this, you can refer to the previous tutorial
still pending

2023-10-16 15:02 UTC, Voldivh commented on tutorials/06_python_support.md
> +The way Gazebo Transport is implemented, it creates several threads each time a node, publisher, subscriber, etc is created. While this allows us to have a better paralization in processes, a downsid
Done.

2023-10-16 15:02 UTC, Voldivh commented on tutorials/06_python_support.md
> +Open a new terminal and directly run the python script downloaded previously. It is expected that the service responser is running in another terminal for this, you can refer to the previous tutorial
Done.

2023-10-16 15:02 UTC, Voldivh commented on tutorials/06_python_support.md
> +Unfortunately, this feature is not available on python at the moment. However, we can use a service responser created in C++ and make a request to it from a code in python. Taking that into account,
Done.

2023-10-16 15:02 UTC, Voldivh commented on tutorials/06_python_support.md
> +Open two new terminals and directly run the python scripts downloaded previously.
Done.

2023-10-16 15:21 UTC, ahcorde approved these changes

2023-10-16 15:21 UTC, ahcorde commented
Thank you @Voldivh

2023-10-23 20:33 UTC, azeey commented on tutorials/06_python_support.md
> +In this tutorial, we are going to show the functionalities implemented in Python. This features are brought up by creating bindings from the C++ implementation using pybind11. It is important to note
```suggestion
In this tutorial, we are going to show the functionalities implemented in Python. These features are brought up by creating bindings from the C++ implementation using pybind11. It is important to note that not all of C++ features are available yet, on this tutorial we will go over the most relevant features. For more information refer to the [__init__.py](https://github.com/gazebosim/gz-transport/blob/gz-transport13/python/src/__init__.py) file which is a wrapper for all the bindings.
```

2023-10-23 20:33 UTC, azeey commented on tutorials/06_python_support.md
> +In this tutorial, we are going to show the functionalities implemented in Python. This features are brought up by creating bindings from the C++ implementation using pybind11. It is important to note
Can you keep the line width at 120 or so. It makes it easier to do reviews.

2023-10-23 20:33 UTC, azeey commented on tutorials/06_python_support.md
> +```{.py}
I saw you had the directives `#! [complete]` in the example code. Would it be possible to do the same for these, so we don't have to duplicate the example code here?

2023-10-23 20:33 UTC, azeey commented on tutorials/06_python_support.md
> +export PYTHONPATH=$PYTHONPATH:<path to ws>/install/lib/python
This assumes the source installation is colcon. If the user simply installed `gz-transport` using `cmake`, this would be slightly different.

2023-10-23 20:33 UTC, azeey commented on tutorials/06_python_support.md
> +The way Gazebo Transport is implemented, it creates several threads each time a node, publisher, subscriber, etc is created. While this allows us to have a better paralization in processes, a downsid
```suggestion
The way Gazebo Transport is implemented, it creates several threads each time a node, publisher, subscriber, etc is created. While this allows us to have a better parallelization in processes, a downside is possible race conditions that might occur if ownership/access of variables is shared across multiple threads. Even though Python has its [GIL](https://wiki.python.org/moin/GlobalInterpreterLock), all the available features are bindings created for its C++ implementation, in other words, the downsides mentioned before are still an issue to be careful about. We recommend to always use threading locks when working with object that are used in several places (publisher and subscribers). 
```

2023-10-23 20:33 UTC, azeey commented on tutorials/06_python_support.md
> +to use but it can be handy in situations like when we want to control the rate
```suggestion
to use but it can be handy in situations where we want to control the rate
```

2023-10-23 20:33 UTC, azeey commented on tutorials/06_python_support.md
> +In this section of code, we create a *SubscribeOptions* object and use it set message rate (the member `msgs_per_sec`). In our case, the message rate specified is 1 msg/sec. Then, we subscribe to the
```suggestion
In this section of code, we create a *SubscribeOptions* object and use it to set message rate (the member `msgs_per_sec`). In our case, the message rate specified is 1 msg/sec. Then, we subscribe to the topic
```

2023-10-24 14:48 UTC, Voldivh commented on tutorials/06_python_support.md
> +```{.py}
You mean for each or the small parts during the Walkthrough? I did it this way just to keep consistency with it is done on the other tutorials.

2023-10-24 15:53 UTC, Voldivh commented on tutorials/06_python_support.md
> +export PYTHONPATH=$PYTHONPATH:<path to ws>/install/lib/python
Done.

2023-10-24 15:53 UTC, Voldivh commented on tutorials/06_python_support.md
> +The way Gazebo Transport is implemented, it creates several threads each time a node, publisher, subscriber, etc is created. While this allows us to have a better paralization in processes, a downsid
Done.

2023-10-24 15:53 UTC, Voldivh commented on tutorials/06_python_support.md
> +to use but it can be handy in situations like when we want to control the rate
Done.

2023-10-24 15:53 UTC, Voldivh commented on tutorials/06_python_support.md
> +In this section of code, we create a *SubscribeOptions* object and use it set message rate (the member `msgs_per_sec`). In our case, the message rate specified is 1 msg/sec. Then, we subscribe to the
Done.

2023-10-24 15:53 UTC, Voldivh commented on tutorials/06_python_support.md
> +In this tutorial, we are going to show the functionalities implemented in Python. This features are brought up by creating bindings from the C++ implementation using pybind11. It is important to note
Done.

2023-10-24 15:53 UTC, Voldivh commented on tutorials/06_python_support.md
> +In this tutorial, we are going to show the functionalities implemented in Python. This features are brought up by creating bindings from the C++ implementation using pybind11. It is important to note
Done.

2023-10-31 15:20 UTC, azeey commented on tutorials/06_python_support.md
> +```{.py}
Okay, I'll approve as is, but I think it's better to use the doxygen trick instead of duplicating the code. The other tutorials should also be doing the same.

2023-10-31 15:21 UTC, azeey approved these changes

2023-11-03 13:28 UTC, merged