Allow programmatic configuration of unicast relays.
gazebosim/gz-transport pull request #497
Opened 2024-04-30 18:33 UTC by mbeards

This change allows users to configure relays from code without having to `setenv(GZ_RELAY)`.

# 🎉 New feature

## Summary
This change allows users to configure relays from code without having to `setenv(GZ_RELAY)`.

## Test it
This can be tested by starting a Node across a boundary where multicast isn't enabled, and setting the relay IP via NodeOptions.

## Checklist
- [ ] Signed all commits for DCO
- [ ] Added tests
- [ ] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.

2024-04-30 20:58 UTC, ahcorde commented on include/gz/transport/Discovery.hh
> +        memset(&addr, 0, sizeof(addr));
include `<cstring>`

2024-04-30 20:58 UTC, ahcorde commented on src/NodeOptions.cc
> +bool NodeOptions::SetRelays(const std::vector<std::string>& _relayIPs) {
include `<vector>`

2024-04-30 22:02 UTC, mbeards commented on include/gz/transport/Discovery.hh
> +        memset(&addr, 0, sizeof(addr));
This file already includes <string.h> - should I swap the include?

2024-05-06 17:00 UTC, caguero requested changes
My main problem with this patch is that so far `NodeOptions` are all options that affect a single node. However, adding relays will have a global impact in all the nodes.

I understand that we don't have a way to set global options right now. Perhaps an alternative could be to not use `NodeOptions` and just create an `AddGlobalRelay()` function in Node()` to preserve the semantics of `NodeOptions`? What do you think?

2024-05-06 17:14 UTC, mbeards commented on include/gz/transport/Discovery.hh
> -      /// \brief Register a new relay address.
I moved it up to sit with the other public functions. ("Group similar declarations together, placing public parts earlier." https://google.github.io/styleguide/cppguide.html#Declaration_Order)

2024-05-06 17:16 UTC, mbeards commented
> My main problem with this patch is that so far `NodeOptions` are all options that affect a single node. However, adding relays will have a global impact in all the nodes.

Agreed that this is weird / gross. I guess ideally I'd want to have accessors for the global Discovery instances, but threading that through seems difficult.

> I understand that we don't have a way to set global options besides using environment variables right now. Perhaps an alternative could be to not use `NodeOptions` and just create an `AddGlobalRelay()` / `GlobalRelays()` functions in `Node` to preserve the semantics of `NodeOptions`? What do you think?

You're thinking something like the following?
```
class Node {
  // ...
  public: static void AddGlobalRelay(const std::string&);
  public: static std::vector<std::string>& Relays();
  // ...
}
```

2024-05-06 17:29 UTC, caguero commented
> > My main problem with this patch is that so far `NodeOptions` are all options that affect a single node. However, adding relays will have a global impact in all the nodes.
> 
> Agreed that this is weird / gross. I guess ideally I'd want to have accessors for the global Discovery instances, but threading that through seems difficult.
> 
> > I understand that we don't have a way to set global options besides using environment variables right now. Perhaps an alternative could be to not use `NodeOptions` and just create an `AddGlobalRelay()` / `GlobalRelays()` functions in `Node` to preserve the semantics of `NodeOptions`? What do you think?
> 
> You're thinking something like the following?
> 
> ```
> class Node {
>   // ...
>   public: static void AddGlobalRelay(const std::string&);
>   public: static std::vector<std::string>& Relays();
>   // ...
> }
> ```

Probably `AddGlobalRelay()` and `GlobalRelays()`.

2024-05-07 17:26 UTC, mbeards commented
> > You're thinking something like the following?
> > ```
> > class Node {
> >   // ...
> >   public: static void AddGlobalRelay(const std::string&);
> >   public: static std::vector<std::string>& Relays();
> >   // ...
> > }
> > ```
> 
> Probably `AddGlobalRelay()` and `GlobalRelays()`.

Done in https://github.com/gazebosim/gz-transport/pull/498

2024-05-24 17:56 UTC, closed without merging