Jrivero/simplify docker
gazebosim/gz-transport pull request #530
Opened 2024-09-02 16:03 UTC by j-rivero

# 🎉 New feature

Simplify the docker setup for the relay example by removing the build.sh and run.sh scripts that were adding helpers for development but were really not needed to run the important code.

## Summary
The two commits are self-explanatory:

 * 5e55b3f41556dce13797fd8068385ea693758a0d simplifies the Dockerfile in place and move it to Ubuntu Noble
 * 9318d585deb58881dd66552081b315cd15e59d50 removes all the jazz added to run docker and replace it on the instructions

## Test it
I've verified that it builds just fine. @caguero verified that it runs fine.

## Checklist
- [x] Signed all commits for DCO
- [ ] Added tests
- [x] Added example and/or tutorial
- [ ] Updated documentation (as needed)
- [ ] Updated migration guide (as needed)
- [ ] Consider updating Python bindings (if the library has them)
- [ ] `codecheck` passed (See [contributing](https://gazebosim.org/docs/all/contributing#contributing-code))
- [ ] All tests passed (See [test coverage](https://gazebosim.org/docs/all/contributing#test-coverage))
- [ ] While waiting for a review on your PR, please help review [another open pull request](https://github.com/pulls?q=is%3Aopen+is%3Apr+user%3Agazebosim+archived%3Afalse+) to support the maintainers

**Note to maintainers**: Remember to use **Squash-Merge** and edit the commit message to match the pull request summary while retaining `Signed-off-by` messages.
gazebo-release) (as needed): <LINK>

2024-09-02 16:12 UTC, caguero commented on docker/Dockerfile
> +# Ubuntu 22.04
Nit: 24.04

2024-09-02 16:12 UTC, caguero commented on docker/Dockerfile
> + && /bin/sh -c 'echo "deb [trusted=yes] http://packages.osrfoundation.org/gazebo/ubuntu-prerelease `lsb_release -cs` main" > /etc/apt/sources.list.d/gazebo-prerelease.list' \
I used this for testing but I think we should remove it.

2024-09-02 16:12 UTC, caguero commented on tutorials/08_relay.md
> +docker build -t gz-transport-relay - < Dockerfile
`docker build -t gz-transport-relay - < gz-transport/Dockerfile`?

2024-09-02 16:30 UTC, caguero requested changes
Retarget to `gz-transport14`?

2024-09-04 15:10 UTC, j-rivero commented on tutorials/08_relay.md
> -Inside the docker instance, go to the `example` directory:
The final `WORKDIR` at the end of the Dockerfile should leave you exactly in that directory ready to run the example binary https://github.com/gazebosim/gz-transport/pull/530/files#diff-f34da55ca08f1a30591d8b0b3e885bcc678537b2a9a4aadea4f190806b374ddcR64

2024-09-04 15:11 UTC, j-rivero commented on docker/Dockerfile
> +# Ubuntu 22.04
[921aa51](https://github.com/gazebosim/gz-transport/pull/530/commits/921aa519291591b5117176ad8a3f374fd3988d26)

2024-09-04 15:21 UTC, caguero approved these changes

2024-09-04 15:28 UTC, merged